version: "3"
services:
  redis:
    image: redis:latest

  db:
    image: postgres:15-alpine 
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      
  vote:
    image: enabdelhamed/voteapp:latest
    ports:
      - 5000:80
    depends_on:
      - redis
  
  worker:
    image: enabdelhamed/worker
    

  result: 
    image: enabdelhamed/result:latest
    ports:
      - 5001:80
  
