# Create Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-sa
---
# Create Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
rules:
- apiGroups: [ "" ]
  resources: [ "pods" ]
  verbs: [ "get", "watch", "list" ]
---
# Create Role Binding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-binding
subjects:
- kind: ServiceAccount
  name: pod-sa
  namespace: default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
# Create a Pod that uses the Service Account
apiVersion: v1
kind: Pod
metadata:
  name: pod-sa-demo
spec:
  serviceAccountName: pod-sa
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
