# The Service will route traffic to the Pods that have the label "env: prod" on port 80.
apiVersion: v1
kind: Service
metadata:
  name: Dolfined-service
  labels:
    tier: Backend
spec:
  type: ClusterIP
  selector:
    env: prod
  ports:
  - protocol: TCP
    port: 80 # The port that the service will expose. This is the port that clients will use to access the service.
    targetPort: 80 # The port that the service will listen on. This is the port that clients will use to access the service.

#
---
apiVersion: v1
kind: Service
metadata:
  name: BackendService
  labels:
    tier: Backend
spec:
  type: loadBalancer
  selector:
    env: prod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

# The Service will route traffic to the Pods that have the label "env: prod" on port 80. The type of the service is LoadBalancer, which means that it will create an external load balancer that will route traffic to the service.
